bookname: Onestop-tumikiban
booktitle: 積み基板を作らないための電子工作入門
aut: []
language: ja
toc: true
rights: (C) 2021　親方Project
colophon: true
history:
  - - 2021-12-31 電子版　初版
pbl: 親方Project
edt: 親方Project　@oyakata2438
date: '2021-12-31'
secnolevel: 3
titlepage: true
review_version: 5.0
texstyle:
  - reviewmacro
texdocumentclass:
  - review-jsbook
  - >-
    media=ebook,paper=b5,serial_pagination=true,hiddenfolio=nikko-pc,openany,fontsize=10pt,baselineskip=15.4pt,line_length=44zw,number_of_lines=40,head_space=18mm,headsep=3mm,headheight=5mm,footskip=10mm
